#!/bin/bash

nsteps=3600  # k (x1000)
f=10000	# max force
sup=100 # suppress for mutex
dt=0.001 # 1ms step size
sample_period=100 # sample every 1, 10, or 100 steps for plotting
sample_size=2000 # from first or last
extension=test3	# file extension, *.train or *test1 ...

#prefix="${nsteps}k-test1" # output file
prefix="${nsteps}k-f$f-mutex$sup-dt${dt}-sample1-r1" # output file same as source file
sourcefile="${prefix}.$extension" # source file
lastlines=$(( nsteps * 1000 - sample_size ))

./gnuplot $prefix $sourcefile $sample_period $lastlines $sample_size
#./gnuplot $nsteps $prefix $sourcefile $sample_period $lastlines

mkdir ${prefix}-${extension}
mv ${prefix}-*.png ${prefix}-${extension}
